# Generated by Django 4.1.13 on 2023-11-16 23:48

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindex',
            name='body',
            field=wagtail.fields.StreamField([('visual', wagtail.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'image', 'embed', 'code', 'superscript', 'subscript', 'strikethrough', 'blockquote'])), ('html', wagtail.blocks.RawHTMLBlock())], blank=True, use_json_field=True),
        ),
    ]
